### PR TITLE
Removed Unknown Directive Validation

### LINKED ISSUE #275: unknown directive "connection"
I am trying to implement pagination following the apollo documentation and it introduce the `@connection` directive for assigning a store key. Using apollo-codegen with the directive causes the `Unkown directive "connection"` error, which I understand is because it doesn't know about the directive.

Is defining the directive in the graphql schema the correct location that this needs to be defined or should the codegen know about the directive and handle the error?

### PR DESCRIPTION
**Pull request by 0xcaff**
Closes #275, #366

### CODE REVIEW

**Comment by lewisf** [comment]
@martijnwalraven do you mind taking a look at this? i think you have more context into why this was added in the first place

**Comment by martijnwalraven** [comment]
We may want to revisit this later, because the unknown directives rule is part of the GraphQL spec and allows us to make sure an operation is valid before we generate code. That probably means we'd need to modify the schema to include client-side directives however.

**Comment by 0xcaff** [comment]
When will a new version with the flow fixes and this fix be released?

**Comment by 0xcaff** [comment]
A release was cut recently. https://github.com/apollographql/apollo-codegen/releases/tag/v0.18.4

**Pull request merged**
