### PR TITLE
Top-line __typename is not a string anymore

### LINKED ISSUE #183: [TS] Use all possible strings for interface types rather than using "string"
As of a couple version ago `apollo-codegen` has been pretty amazing. The majority of the use cases around fragments were solved, but I've found a small issue.

When interfaces are used, the `__typename` is split out into a discriminated union when different data types are used. If you only fetch field from the top-line interface, however, it will generate the `__typename` simply as `string`. This is an issue if you try to combine fragments for an implementation with a fragment for the interface.

For example, if FooBar implements the Foo interface Typescript complains that `string` isn't compatible with `FooBar` when combining these fragments together.

When dealing with interface / union types, this would be solved by **always** using all available types in a union type rather than `string`.

### PR DESCRIPTION
**Pull request by rricard**
Replaced with the correct type name

Fixes #183

### CODE REVIEW

**Comment by rricard** [comment]
@lewisf I'd like your review for two things:

- can we be more efficient/cleaner on this
- does it really fix #183? I don't think I have the right test cases to see it...

**Comment by rricard** [comment]
This is definitely something we could generalize in the IR (cc @martijnwalraven), I'll try to apply your diff to see if I can test it correctly.

**Comment by lewisf** [comment]
I haven't tested that code :P hopefully that works though (or something along those lines)

**Comment by rricard** [comment]
@lewisf it works! I'll create an issue to track the refactor into the IR.

**Pull request merged**
