### PR TITLE
[typescript-modern] Preventing printer of unused enums

### PR DESCRIPTION
**Pull request by gullitmiranda**
Fixing [src/javascript/typescript/codeGeneration.ts](https://github.com/apollographql/apollo-codegen/compare/master...gullitmiranda:feature/preventing-unused-enums?expand=1#diff-9ea27addf052270339ea1d558706efdd) generate unused enums.

this PR includes #368

### CODE REVIEW

**Comment by lewisf** [comment]
thank you @gullitmiranda ! this is awesome :) do you mind rebasing master to pick up test fixes from master? meanwhile I'm going to review this when i get the chance

**Comment by gullitmiranda** [comment]
I don't mind, I did not initially because the master was broken

Gullit Miranda

Em 15 de fev de 2018 19:31, "Lewis Chung" <notifications@github.com>
escreveu:

**Comment by gullitmiranda** [comment]
rebase done!

**Comment by shadaj** [comment]
Merged in https://github.com/apollographql/apollo-codegen/commit/27af78a9afe04c5a3ea098fa10758a05980794bd!

**Pull request closed without merging**
