### PR TITLE
feat: make the tag name configurable (fixes #119)

### LINKED ISSUE #119: Make the tag name configurable
I've opted to use `graphql` tag instead of `gql`. It would be useful if `apollo-codegen` provided tag-name as an option.

Happy to raise a PR.

### PR DESCRIPTION
**Pull request by gajus**

### CODE REVIEW

**Comment by rricard** [comment]
Hey @gajus, I'm sorry, we weren't really around here lately. I think we can definitely merge that if you rebase it! If you don't have time to do it, I can also do it.

**Comment by rricard** [comment]
Also, will fix #120

**Comment by lewisf** [comment]
Because the tag-name is only a Flow/Typescript thing -- let's add that to the help string.

**Comment by lewisf** [comment]
continued this work in #148 (rebase and add the thing I requested originally). thanks for the contribution @gajus !

**Pull request closed without merging**
