### PR TITLE
Add typeName for nested property objects

### PR DESCRIPTION
**Pull request by leethree**
This is the fixed version of #294. The only difference is in commit c7d387f96140ec532519c4719b531a5ffebf00ca.

### CODE REVIEW

**Comment by annalo** [comment]
Any news on getting this merged?

**Comment by leethree** [comment]
@lewisf could you take a look at this?

**Comment by zapo** [comment]
We're using this in our fork successfully, we just had to fix compilation with this commit:
https://github.com/adgear/apollo-codegen/commit/11e5d6be12757dfdef59b084f4642d02ebea0e22 (missing a null-check)

**Comment by leethree** [comment]
@zapo Thanks for your comment! I rebased this branch to master and fixed the compilation issue.

**Comment by lewisf** [comment]
thanks for the contribution @leethree! apologies for taking so long to take a look at this

**Pull request merged**
