### PR TITLE
add tests and docs for `gql` template usage

### PR DESCRIPTION
**Pull request by itajaja**
It's just one giant catch-all test, if it doesn't meet your quality standards I can definitely do something more granular :)

### CODE REVIEW

**Comment by lewisf** [comment]
do you mind moving the test to a new file, maybe `tests/loading.js`?

**Comment by itajaja** [comment]
Sounds good

**Comment by itajaja** [comment]
anything else missing?

**Comment by lewisf** [comment]
sorry, been sick :( this looks good!

**Pull request merged**
