### PR TITLE
[feedback] add functionality to extract gql document from gql template

### PR DESCRIPTION
**Pull request by itajaja**
addresses #25 

this is clearly very hap hazard, because regex is not the best tool for doing this job, but this should work for most simple cases, like:

```js
const Query = gql`
  query Foo($id: String!) {
    foo(fooId: $id) {
      ...BarFragment
    }
  }
  ${barFragment}
`
```

The alternative would be to use a different parser for ts/js/swift, but that's a much bigger effort

### CODE REVIEW

**Comment by lewisf** [comment]
I think this actually will work for all cases since it works in persistgraphql. I like going with this for simplicity for now.

Are there any cases that wouldn't work?

**Comment by itajaja** [comment]
I have been playing with this snippet for a while and it seems to handle all the use cases I threw at it, like multiple `gql` templates in one file, multiple fragments, etc.

**Comment by itajaja** [comment]
If this looks ok, I can add docs + tests over the we

**Comment by lewisf** [comment]
Yeah, this is totally reasonable, I'll merge this in now and it'll be ready with the next release. Adding docs/tests would be great :)

**Comment by itajaja** [comment]
great! thanks for the speedy review 👍

**Pull request merged**
