### PR TITLE
Alternate implementation of propertyAssignmentForField to avoid “Ambiguous use of ‘map’” error

### PR DESCRIPTION
**Pull request by plarson**
This is an alternate output for propertyAssignmentForField that avoids the "Ambiguous use of 'map'" error described here: https://github.com/apollographql/apollo-ios/issues/178

### CODE REVIEW

**Comment by horsejockey** [comment]
@plarson Thanks for building this fix. I'm just running into it now.  Any word on when this might get merged?

**Comment by martijnwalraven** [comment]
@plarson Sorry, I missed this because of the holiday break. Great work! Before I can merge it, I'd need you to sign the CLA and we'd want the tests to reflect the changes so they pass.

**Comment by martijnwalraven** [comment]
@plarson I'd love to merge this, but before I can do that I really need you to sign the CLA.

**Comment by matteinn** [comment]
@plarson any news here? It would be awesome to have this merged :)

**Comment by annjose** [comment]
Our team also faces the same code generation issue with multiple variables in mutation. Hence this PR is very important for us also. @plarson Thanks you for fixing this. Please get this merged as soon as possible. cc @martijnwalraven

**Comment by martijnwalraven** [comment]
I'd really like to merge this, but I can't merge code without the author signing the CLA @plarson

**Comment by martijnwalraven** [comment]
@frenchdonuts Yes, that would be great!

**Comment by RabeaWahab** [comment]
It would be great if that can be merged 👍

**Comment by annjose** [comment]
Yes @frenchdonuts - please merge. It would be awesome 👍

**Comment by frenchdonuts** [comment]
Hi all, I don't have time to go through the fixes right now. However, I found a temporary fix-around. I don't know why this works (for me), but it does.
1) Click "Discard all changes" under the "Source Control" menu in XCode.
2) Run pod install.
3) Build and run

**Comment by martijnwalraven** [comment]
I need to fix some tests and check with the Flow and TypeScript targets before releasing a new version, but I hope we can get a new version out next week.

**Comment by martijnwalraven** [comment]
It turned out the code I merged wasn't actually correct, but I rewrote it and it now seems to be working. All the Apollo iOS tests pass with the new codegen.

This was released as `apollo-codegen` 0.18.4, which Apollo iOS 0.8.0 depends on.

**Comment by martijnwalraven** [comment]
Would be great to hear how this is working for people!

**Pull request merged**
