### PR TITLE
--passthroughCustomScalars option was not handled in Typescript generator

### PR DESCRIPTION
**Pull request by Bolisov**
This is fix for https://github.com/apollographql/apollo-codegen/issues/223

### CODE REVIEW

**Comment by Bolisov** [comment]
> @Bolisov: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Meteor Contributor Agreement here: https://contribute.meteor.com/

signed...

**Comment by martijnwalraven** [comment]
@Bolisov: Hmmm, maybe something went wrong with the signing or the notification to GitHub? Could you try again?

**Comment by Bolisov** [comment]
Great, now it is signed )

**Comment by martijnwalraven** [comment]
Great, thanks!

**Pull request merged**
