### PR TITLE
Generate types for all nested object types in Flow

### LINKED ISSUE #159: Proposal: Expose types for nested objects in Flow/Typescript targets
Right now, for the Flow and Typescript targets, we generate 1:1 types per operation and fragment.

I have a fork that generates nested types and we've been using this. I was wondering how useful this would be to other people and if we should pull this into master.

The type names that are generated can get very verbose, but having all the intermediate types allows for more flexibility around how the types are used.

cc @rricard I know we talked about this before. The code change is fairly minimal to get this to work.

For instance, for the following GraphQL:

```graphql
query HeroQuery {
  hero(episode:NEWHOPE) {
    name
    friends {
      ... on Droid {
        primaryFunction
      }
      ... on Human {
        appearsIn
        homePlanet
        friends {
          ... on Droid {
            primaryFunction
          }

          ... on Human {
            homePlanet
          }
        }
      }
    }
  }
}
```

we generate a type like this.

```javascript
/* @flow */
//  This file was automatically generated and should not be edited.

export type HeroQueryQuery = {|
  hero: ?( {
      __typename: "Human",
      // The name of the character
      name: string,
      // The friends of the character exposed as a connection with edges
      friendsConnection: {|
        __typename: string,
        // A list of the friends, as a convenience when edges are not needed.
        friends: ?Array< ( {
            __typename: "Human",
            // The name of the character
            name: string,
          } | {
            __typename: "Droid",
            // The name of the character
            name: string,
          }
        ) >,
      |},
    } | {
      __typename: "Droid",
      // The name of the character
      name: string,
      // The friends of the character exposed as a connection with edges
      friendsConnection: {|
        __typename: string,
        // A list of the friends, as a convenience when edges are not needed.
        friends: ?Array< ( {
            __typename: "Human",
            // The name of the character
            name: string,
          } | {
            __typename: "Droid",
            // The name of the character
            name: string,
          }
        ) >,
      |},
    }
  ),
|};

export type CharacterFragmentFragment = ( {
      __typename: "Human",
      // The name of the character
      name: string,
    } | {
      __typename: "Droid",
      // The name of the character
      name: string,
    }
  );
```

Generating named types for all the nested objects looks like this.

```javascript
/* @flow */
//  This file was automatically generated and should not be edited.

/* GraphQL Operation: HeroQuery */

export type HeroQueryQuery = {|
  hero: ?(HeroQueryQuery_hero_Human | HeroQueryQuery_hero_Droid),
|};

export type HeroQueryQuery_hero_Droid = {|
  __typename: "Droid",
  // The name of the character
  name: string,
  // The friends of the character exposed as a connection with edges
  friendsConnection: HeroQueryQuery_hero_Droid_friendsConnection,
|};

export type HeroQueryQuery_hero_Droid_friendsConnection = {|
  __typename: string,
  // A list of the friends, as a convenience when edges are not needed.
  friends: ?Array< (HeroQueryQuery_hero_Droid_friendsConnection_friends_Human | HeroQueryQuery_hero_Droid_friendsConnection_friends_Droid) >,
|};

export type HeroQueryQuery_hero_Droid_friendsConnection_friends_Droid = {|
  __typename: "Droid",
  // The name of the character
  name: string,
|};

export type HeroQueryQuery_hero_Droid_friendsConnection_friends_Human = {|
  __typename: "Human",
  // The name of the character
  name: string,
|};

export type HeroQueryQuery_hero_Human = {|
  __typename: "Human",
  // The name of the character
  name: string,
  // The friends of the character exposed as a connection with edges
  friendsConnection: HeroQueryQuery_hero_Human_friendsConnection,
|};

export type HeroQueryQuery_hero_Human_friendsConnection = {|
  __typename: string,
  // A list of the friends, as a convenience when edges are not needed.
  friends: ?Array< (HeroQueryQuery_hero_Human_friendsConnection_friends_Human | HeroQueryQuery_hero_Human_friendsConnection_friends_Droid) >,
|};

export type HeroQueryQuery_hero_Human_friendsConnection_friends_Droid = {|
  __typename: "Droid",
  // The name of the character
  name: string,
|};

export type HeroQueryQuery_hero_Human_friendsConnection_friends_Human = {|
  __typename: "Human",
  // The name of the character
  name: string,
|};
/* GraphQL Fragment: CharacterFragment */

export type CharacterFragmentFragment = (CharacterFragmentFragment__Human | CharacterFragmentFragment__Droid);
export type CharacterFragmentFragment__Droid = {|
  __typename: "Droid",
  // The name of the character
  name: string,
|};

export type CharacterFragmentFragment__Human = {|
  __typename: "Human",
  // The name of the character
  name: string,
|};
```

Any thoughts?

### PR DESCRIPTION
**Pull request by lewisf**
Fixes #159 

1. Please view snapshots to see the changes.
2. Please view the code and let me know if anything about it is confusing / can be cleaned up

### CODE REVIEW

**Comment by rricard** [comment]
I'll take a look at it today if I can. Thanks!

**Comment by lewisf** [comment]
I noticed there's double underscores on some fragment cases. I need to look into that to see why that's happening

**Comment by rricard** [comment]
@lewisf this is awesome, and I actually see this as an opportunity to simplify drastically the whole codebase. Since we're not going to have multiple blocks, indent level and all that stuff, maybe we could have a transform that would just return a list of types from an IR tree with their props and types and that's pretty much it! We will not need to recursively go through the tree, just output each level... I'd like to merge that now but I'm waiting for #197 to be merged first and this one rebased on it. Then, I can merge, and then, I'll port that to TS, and then, I'll start working on what's common and not common between targets to write smaller language modules.

**Comment by liyucun** [comment]
@rricard I would love to have the same functionality for typescript...

**Comment by lewisf** [comment]
Closed in favor of #296 and #304 which will support this

**Pull request closed without merging**
